<a href="https://colab.research.google.com/github/munizgui/CP4_SERS/blob/main/CP4_SERS_EX4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset 4 - Solar Power Generation Data (Kaggle)

fonte:https://www.kaggle.com/datasets/anikannal/solar-power-generation-data

Situação

Dados de geração e sensores de duas usinas fotovoltaicas, com medições realizadas em inversores e sensores ambientais.

In [ ]:
import pandas as pd

In [ ]:
df4 = pd.read_csv("Plant_2_Generation_Data_SAMPLE04(in).csv")

In [ ]:
df4 = df4.rename(columns={
    "DC_POWER": "Potencia_CC",
    "AC_POWER": "Potencia_AC",
    "DAILY_YIELD": "Geracao_Diaria"
})

In [ ]:
df4.head()

,DATE_TIME,SOURCE_KEY,Potencia_CC,Potencia_AC,Geracao_Diaria,TOTAL_YIELD
0,2020-05-28 10:00:00,vOuJvMaM2sgwLmb,1090.240,1063.560,2079.21,2.307960e+06
1,2020-06-16 11:15:00,81aHJ1q11NBPMrL,740.613,724.827,2209.60,1.215480e+09
2,2020-05-17 18:45:00,Qf4GUc1pJu5T6c6,0.000,0.000,7220.00,8.384430e+08
3,2020-05-21 23:00:00,q49J1IKaHRwDQnt,0.000,0.000,4844.00,3.741710e+05
4,2020-06-05 23:15:00,vOuJvMaM2sgwLmb,0.000,0.000,3421.00,2.356530e+06

In [ ]:
df4.shape

(13540, 6)

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13540 entries, 0 to 13539
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DATE_TIME       13540 non-null  object
 1   SOURCE_KEY      13540 non-null  object
 2   Potencia_CC     13540 non-null  float64
 3   Potencia_AC     13540 non-null  float64
 4   Geracao_Diaria  13540 non-null  float64
 5   TOTAL_YIELD     13540 non-null  float64
dtypes: float64(4), object(2)
memory usage: 634.8+ KB

In [ ]:
df4.describe()

        Potencia_CC   Potencia_AC  Geracao_Diaria   TOTAL_YIELD
count  13540.000000  13540.000000    13540.000000  1.354000e+04
mean     244.934106    239.550853     3307.097232  6.478274e+08
std      369.464843    361.031313     2932.391403  7.206826e+08
min        0.000000      0.000000        0.000000  0.000000e+00
25%        0.000000      0.000000      271.724000  1.996630e+07
50%        0.000000      0.000000     2930.235000  2.826160e+08
75%      444.312500    435.801250     5556.000000  1.348470e+09
max     1401.310000   1366.260000     9873.000000  2.247920e+09

MAIOR POTÊNCIA CA

In [ ]:
potencia_ca_max = df4["Potencia_AC"].max()
print(f"Maior Potencia_CA registrada: {potencia_ca_max}")

Maior Potencia_CA registrada: 1366.26

CALCULO DO LIMIAR CORRESPONDENTE A 70%

In [ ]:
limiar_alta_geracao = potencia_ca_max * 0.70
print(f"Limiar (70%): {limiar_alta_geracao:.2f}")

Limiar (70%): 956.38

CRIANDO DATAFRAME E CALCULE O PERCENTUAL

In [ ]:
df_alta_geracao = df4[df4['Potencia_AC'] > limiar_alta_geracao]

qtd_alta = len(df_alta_geracao)
pct_alta = (qtd_alta / len(df4)) * 100

print(f"Quantidade de registros de alta geração: {qtd_alta}")
print(f"Percentual em relação ao total: {pct_alta:.2f}%")

Quantidade de registros de alta geração: 1019
Percentual em relação ao total: 7.53%

INDENTIFICANDO FREQUÊNCIA DE INVERSOR

In [ ]:
frequencia_inversores = df_alta_geracao['SOURCE_KEY'].value_counts()

print("--- Frequência de Inversores em Alta Geração ---")
print(frequencia_inversores)
print("O resultado permite observar que este inversor específico atinge picos de geração máxima com maior frequência ou sustenta a operação em alta potência por mais tempo do que os outros dentro desta amostra.")