<a href="https://colab.research.google.com/github/munizgui/CP4_SERS/blob/main/CP4_SERS_EX3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset 3 - Power Consumption of Tetouan City (UCI)

fonte: https://archive.ics.uci.edu/dataset/849/power+consumption+of+tetouan+city

Situação

Consumo elétrico de três zonas de distribuição da cidade de Tétouan, associado a variáveis meteorológicas.

In [ ]:
import pandas as pd

In [ ]:
df3 = pd.read_csv("Tetuan City power consumption_SAMPLE03 1.csv")

In [ ]:
df3.head()

,DateTime,Temperature,Humidity,Wind Speed,Zone 1 Power Consumption,Zone 3 Power Consumption,Zone 2 Power Consumption
0,4/18/2017 16:20,22.76,29.73,0.085,32985.14532,17623.3,19396.7
1,12/27/2017 17:10,15.92,54.44,0.085,34737.64259,14417.3,29803.0
2,1/2/2017 11:20,15.08,57.23,0.076,27894.68354,16458.8,20808.5
3,3/19/2017 20:20,12.42,72.30,0.081,42476.93617,25089.7,23634.1
4,4/24/2017 5:50,14.58,80.60,0.080,21341.14101,11531.6,12006.1

In [ ]:
df3.shape

(7863, 7)

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7863 entries, 0 to 7862
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   DateTime                   7863 non-null   object
 1   Temperature                7863 non-null   float64
 2   Humidity                   7863 non-null   float64
 3   Wind Speed                 7863 non-null   float64
 4   Zone 1 Power Consumption   7863 non-null   float64
 5   Zone 3  Power Consumption  7863 non-null   float64
 6   Zone 2  Power Consumption  7863 non-null   float64
dtypes: float64(6), object(1)
memory usage: 430.1+ KB

In [ ]:
df3.describe()

,Temperature,Humidity,Wind Speed,Zone 1 Power Consumption,Zone 3 Power Consumption,Zone 2 Power Consumption
count,7863.000000,7863.000000,7863.000000,7863.000000,7863.000000,7863.000000
mean,18.789376,68.400612,1.965602,32371.549651,17845.600069,21060.733609
std,5.864564,15.665773,2.350954,7134.686966,6573.203996,5202.357437
min,3.541000,13.340000,0.054000,14612.658230,6211.760000,9436.250000
25%,14.340000,58.485000,0.078000,26263.115455,13200.700000,17013.400000
50%,18.690000,70.000000,0.086000,32249.429660,16490.300000,20851.600000
75%,22.820000,81.500000,4.915000,37421.355555,21763.600000,24812.200000
max,39.600000,94.700000,6.325000,51571.498340,47441.700000,36437.200000

1-RENOMEANDO AS ZONAS

In [ ]:
df3 = df3.rename(columns={
    "Zone 1 Power Consumption": "Consumo_Zona_1",
    "Zone 2  Power Consumption": "Consumo_Zona_2",
    "Zone 3  Power Consumption": "Consumo_Zona_3"
})

In [ ]:
df3.columns

Index(['DateTime', 'Temperature', 'Humidity', 'Wind Speed', 'Consumo_Zona_1',
       'Consumo_Zona_3', 'Consumo_Zona_2'],
      dtype='object')

2-MAIORES VALORES DE CADA ZONA

In [ ]:
maximos = df3[
    ["Consumo_Zona_1", "Consumo_Zona_2", "Consumo_Zona_3"]
].max()
print(f"os maiores valores de cada zona são, respectivamente: {maximos}")

os maiores valores de cada zona são, respectivamente: Consumo_Zona_1    51571.49834
Consumo_Zona_2    36437.20000
Consumo_Zona_3    47441.70000
dtype: float64

3-ZONA COM MAIOR PICO DE CONSUMO

In [ ]:
zona_maior_pico = maximos.idxmax()
maior_pico = maximos.max()

print(f"Zona com maior pico: {zona_maior_pico}")
print(f"Valor máximo: {maior_pico}")

Zona com maior pico: Consumo_Zona_1
Valor máximo: 51571.49834

4-70% DO VALOR MAXIMO

In [ ]:
limiar = 0.70 * maior_pico

print(f"Limiar (70% do máximo): {limiar}")

Limiar (70% do máximo): 36100.048837999995

In [ ]:
df3_acima_limiar = df3[df3[zona_maior_pico] > limiar].copy()
print(df3_acima_limiar)

              DateTime  Temperature  Humidity  Wind Speed  Consumo_Zona_1  \
3      3/19/2017 20:20        12.42     72.30       0.081     42476.93617
8     12/10/2017 17:50        14.66     65.92       0.075     37286.69202
12      6/5/2017 23:30        21.03     86.50       0.068     40993.90728
14     8/23/2017 17:50        27.06     47.58       4.905     37475.16093
19      6/22/2017 2:40        19.20     65.81       4.924     40676.02649
...                ...          ...       ...         ...             ...
7848    9/7/2017 20:00        24.88     68.59       0.265     46863.71681
7851   10/6/2017 13:40        25.58     42.21       4.919     36898.03063
7855   9/27/2017 19:40        22.31     78.40       4.919     48036.10619
7858   2/17/2017 22:40        10.62     82.90       0.075     37031.18644
7860   2/11/2017 18:50        13.44     74.70       0.076     43328.13559

      Consumo_Zona_3  Consumo_Zona_2
3            25089.7         23634.1
8            15834.8         30716.2
12           24960.0         25383.4
14           25140.6         24276.2
19           25095.9         24754.7
...              ...             ...
7848         23716.6         28186.3
7851         12944.0         22922.0
7855         21110.2         28414.6
7858         22507.4         21793.3
7860         25963.4         25619.5

[2388 rows x 7 columns]

5-CONTAR OS REGISTROS E CALCULAR OS PERCENTUAIS

In [ ]:
quantidade = len(df3_acima_limiar)
total = len(df3)
percentual = (quantidade / total) * 100

print(f"\nRegistros acima do limiar: {quantidade}")
print(f"Percentual da amostra: {percentual:.2f}%")

Registros acima do limiar: 2388
Percentual da amostra: 30.37%

6-TEMPERATURA MÉDIA

In [ ]:
temperatura_media = df3["Temperature"].mean()

print(f"Temperatura média: {temperatura_media:.2f}")

Temperatura média: 18.79

In [ ]:
df3_consumo_temperatura = df3[
    (df3[zona_maior_pico] > limiar) &
    (df3["Temperature"] > temperatura_media)
].copy()

quantidade_com_temperatura = len(df3_consumo_temperatura)
percentual_com_temperatura = (quantidade_com_temperatura / total) * 100

print(f"\nRegistros acima do limiar e acima da temperatura média: "
      f"{quantidade_com_temperatura}")
print(f"Percentual da amostra: {percentual_com_temperatura:.2f}%")

Registros acima do limiar e acima da temperatura média: 1597
Percentual da amostra: 20.31%

7- COMPARAÇÂO DOS CONJUNTOS

In [ ]:
print("\nComparação: Na interpretação final, se a quantidade de registros diminuir após adicionar a temperatura, isso significa que nem todos os períodos de consumo elevado ocorreram sob temperaturas acima da média. A condição ambiental funciona, portanto, como um filtro adicional e torna o conjunto analisado mais restritivo.\n")
print(f"Somente consumo acima do limiar: {quantidade} registros")
print(f"Consumo + temperatura acima da média: "
      f"{quantidade_com_temperatura} registros")
print(f"Redução: {quantidade - quantidade_com_temperatura} registros")

Comparação: Na interpretação final, se a quantidade de registros diminuir após adicionar a temperatura, isso significa que nem todos os períodos de consumo elevado ocorreram sob temperaturas acima da média. A condição ambiental funciona, portanto, como um filtro adicional e torna o conjunto analisado mais restritivo.

Somente consumo acima do limiar: 2388 registros
Consumo + temperatura acima da média: 1597 registros
Redução: 791 registros